spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb+srv://jiho:qz258181%5E%5E@clusterchat.potqui6.mongodb.net/test?retryWrites=true&w=majority&appName=ClusterChat
      auto-index-creation: true

server:
  port: 9000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
